// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs pdf-to-image`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "pdf-split",
    "icon": "✂️",
    "name": {
      "en": "Split PDF",
      "ja": "PDFを分割",
      "zh": "拆分 PDF",
      "de": "PDF teilen",
      "es": "Dividir PDF"
    },
    "desc": {
      "en": "Extract page ranges into a new PDF.",
      "ja": "指定したページ範囲を新しいPDFとして取り出します。",
      "zh": "把指定页码范围提取成新的 PDF。",
      "de": "Seitenbereiche in ein neues PDF extrahieren.",
      "es": "Extrae rangos de páginas en un PDF nuevo."
    }
  },
  {
    "slug": "pdf-merge",
    "icon": "📑",
    "name": {
      "en": "Merge PDF",
      "ja": "PDFを結合",
      "zh": "合并 PDF",
      "de": "PDF zusammenführen",
      "es": "Unir PDF"
    },
    "desc": {
      "en": "Combine several PDFs into one.",
      "ja": "複数のPDFを1つにまとめます。",
      "zh": "把多个 PDF 合成一个。",
      "de": "Mehrere PDFs zu einem zusammenfügen.",
      "es": "Combina varios PDF en uno solo."
    }
  },
  {
    "slug": "pdf-extract-text",
    "icon": "📝",
    "name": {
      "en": "Extract PDF Text",
      "ja": "PDFのテキストを抽出",
      "zh": "提取 PDF 文本",
      "de": "PDF-Text extrahieren",
      "es": "Extraer texto de PDF"
    },
    "desc": {
      "en": "Pull the text out of a PDF into a .txt file.",
      "ja": "PDFのページからテキストを抽出してテキストファイルに。",
      "zh": "把 PDF 中的文本提取为文本文件。",
      "de": "Text aus einem PDF in eine .txt-Datei holen.",
      "es": "Saca el texto de un PDF a un archivo .txt."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'pdf-to-image';
